<?php

/**
 * @file
 * Hook implements for commerce_checkout_api.install.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 * @noinspection PhpUnused
 */
function commerce_checkout_api_install() {
  // Append rest plugin permissions to authenticated role.
  $permissions = [
    'restful post enhanced_promotion_check_coupons_availability',
  ];
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions);
}
