<?php

/**
 * @file
 * Contains enhanced_promotion.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\enhanced_promotion\CouponStockItemList;
use Drupal\enhanced_promotion\CouponUsageItemList;

/**
 * Implements hook_help().
 */
function enhanced_promotion_help($route_name, RouteMatchInterface $route_match): string {
  switch ($route_name) {
    // Main module help for the enhanced_promotion module.
    case 'help.page.enhanced_promotion':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides additional features for Commerce promotion.') . '</p>';
      return $output;
    default:
      return '';
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function enhanced_promotion_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];

  if ($entity_type->id() === 'commerce_promotion_coupon') {

    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Claimed user'))
      ->setSetting('target_type', 'user')
      ->setSetting('handler', 'default')
      ->setDisplayOptions('view', [
        'label' => 'inline',
        'type' => 'entity_reference_label'
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete'
      ])
      ->setDisplayConfigurable('view', true)
      ->setDisplayConfigurable('form', true);

    $fields['usage'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Usage'))
      ->setDescription(t('Usage of this coupon.'))
      ->setComputed(TRUE)
      ->setClass(CouponUsageItemList::class)
      ->setCardinality(1) // You only need this if your computed field is multi-value.
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);
  }

  if ($entity_type->id() === 'commerce_promotion') {

    $fields['image'] = BaseFieldDefinition::create('image')
      ->setLabel(t('Advert image'))
      ->setDescription(t('Image to display for this promotion.'))
      ->setCardinality(1)
      ->setSettings([
        'file_directory' => 'commerce_promotion/promotion/image/[date:custom:Y]-[date:custom:m]',
        'alt_field' => false,
        'title_field' => false,
      ])
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'image'
      ])
      ->setDisplayOptions('form', [
        'type' => 'image_image'
      ]);
  }

  if ($entity_type->id() === 'commerce_promotion') {
    $fields['coupon_stock'] = BaseFieldDefinition::create('coupon_stock')
      ->setLabel(t('Coupon stock'))
      ->setDescription(t('Stock of coupons can be claimed.'))
      ->setComputed(TRUE)
      ->setClass(CouponStockItemList::class)
      ->setCardinality(1) // You only need this if your computed field is multi-value.
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);
  }

  return $fields;
}


/**
 * Implements hook_entity_type_alter().
 */
function enhanced_promotion_entity_type_alter(array &$entity_types): void {

  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */

  // Set the controller class for nodes to an alternate implementation of the
  // Drupal\Core\Entity\EntityStorageInterface interface.
  $entity_types['commerce_promotion']->setLinkTemplate('canonical', '/promotion/{commerce_promotion}');
}
